# FUNDING.yml auto-copied by DevOnboarder Codex
# Maintainer: TAGS Legal & DevRel
# Version: v0.1.0 | Updated: 11 June 2025 03:48 (EST)
# -----------------------------------------------------------------------------
# GitHub Sponsors handle (personal for now)
github:
  - 'reesey275'

# Custom funding links (crypto, Ko-fi, etc.)
# NOTE: This address is **EVM-only**. Send funds via Ethereum, Base,
# Polygon (MATIC), Avalanche, Arbitrum, or BNB Smart Chain. Do **NOT**
# send assets from non-EVM chains.
custom:
  - 'ethereum:0xdE4616365CDf433CA814788404EbDc55ea9C24cB'
