# PATCHED v0.1.57 .github/workflows/ci.yaml — install auth-server deps before tests

name: CI

on:
  pull_request:
  push:
    branches: [main, development]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    env:
      DOMAIN: ${{ secrets.DOMAIN }}
    steps:
      - uses: actions/checkout@v4

      - name: Lint branch name
        if: github.event_name == 'pull_request'
        uses: lekterable/branchlint-action@2.1.0
        with:
          allowed: |
            main
            develop
            /(feat|fix|docs|chore)\/[A-Z]+-\d+/i
          errorMessage: >
            ✖ Branch name doesn't match our convention:
            type/TICKET-1234-short-description

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false


      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'
          cache-dependency-path: frontend/pnpm-lock.yaml

      - name: Install auth-server dependencies
        run: bash scripts/setup-dev.sh

      - name: Start Redis
        run: docker run -d -p 6379:6379 redis:7-alpine

      - name: Wait for Redis
        run: sleep 3

      - name: Run auth-server tests
        run: pnpm --dir auth-server run test

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Set up environment
        run: |
          bash scripts/setup-dev.sh
          source venv/bin/activate
      - name: Install lint dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r .codex/requirements-lint.txt \
            pre-commit

      - name: Run pre-commit
        run: |
          source venv/bin/activate
          ./hooks/pre-commit

      - name: Run pytest
        run: |
          source venv/bin/activate
          pytest --cov --cov-fail-under=85

      - name: Check auth health endpoint
        run: |
          code=$(curl -k -o /dev/null -w '%{http_code}' \
            https://auth.$DOMAIN/healthz)
          test "$code" = "200"
