# PATCHED v0.5.10 .github/workflows/codex.yaml — Add blank line after header

name: codex-agent

on:
  push:
    branches: [ "main", "feature/**" ]

jobs:
  codex:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Build Codex image
        run: docker build -t codex-ci -f Dockerfile.codex .
      - name: Run Codex task
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_KEY }}
        run: |
          docker run --rm \
            -e OPENAI_API_KEY \
            -v "$PWD:/workspace" \
            codex-ci \
            --quiet \
            -a auto-edit \
            "Refactor src/utils/roles.ts to read IDs from env vars"
      - name: Commit Codex changes
        run: |
          git config user.name codex-bot
          git config user.email codex-bot@example.com
          if [[ -n $(git status --porcelain) ]]; then
            git add -A
            git commit -m "feat(codex): auto-refactor roles"
            git push origin HEAD:${{ github.ref_name }}
          fi
